---
config:
  markdownAutoWrap: false
---
flowchart LR;
    A1@{ shape: doc, label: "FAIRification 
    Goal" }
    A2@{ shape: doc, label: "FAIRification 
    Work plan" }
    A3@{ shape: docs, label: "FAIRification 
    Status report" }
    start@{ shape: sm-circ, label: "Iterative FAIRification Cycles" }
    PhaseII@{ shape: process, label: "Post-FAIRification 
    Review"}
    finish@{ shape: framed-circle, label: "End" }
    B1@{ shape: doc, label: "FAIRification 
    Story" }
    B2@{ shape: brace, label: "Requirements met
    Uses enabled
    Lessons learned" }
    A1 -.- A2 -.- A3 -.- start --> PhaseII --> finish -.- B1 -.- B2