flowchart LR;
    A@{ shape: doc, label: "FAIRification Workplan" }
    start@{ shape: sm-circ, label: "Project Examination" }
    subgraph Phase[Iterative FAIRification Cycles]
        direction LR
        Assessment --> Design --> Implementation
        Implementation --> Assessment
    end
    finish@{ shape: framed-circle, label: "Post-FAIRification Review" }
    B1@{ shape: doc, label: "FAIRification Task report" }
    B2@{ shape: brace, label: "Decisions
    Tasks&nbsp;&amp;&nbsp;statuses
    Improvements" }
    A -.- start --> Phase --> finish -.- B1 -.- B2

