%%{init: {
  "markdownAutoWrap": false
}}%%
flowchart LR;
    A1@{ shape: brace-r, label: "FAIR 
    compliance 
    challenge" }
    A2@{ shape: doc, label: "FAIRification<br>Idea" }
    start@{ shape: sm-circ, label: "Small start" }
    PhaseI@{ shape: process, label: "Define 
    FAIRification 
    Goal"}
    finish@{ shape: framed-circle, label: "Stop" }
    B@{ shape: doc, label: "FAIRification 
    Goal" }
    B2@{ shape: brace, label: "In terms of *intended 
    usability* that currently 
    isn’t possible." }
    A1 -.- A2 -.- start --> PhaseI --> finish -.- B -.- B2

    classDef C width:200,padding:0
    class B2 C