flowchart LR;
    A@{ shape: doc, label: "FAIRification Goal" }
    start@{ shape: sm-circ, label: "Define FAIRification Goal" }
    PhaseII@{ shape: process, label: "Project Examination"}
    finish@{ shape: framed-circle, label: "Iterative FAIRification Cycles" }
    B1@{ shape: doc, label: "FAIRification Roadmap" }
    B2@{ shape: brace, label: "Requirements
    Capabilities
    Resources
    Backlog" }
    A -.- start --> PhaseII --> finish -.- B1 -.- B2
