flowchart LR;
        direction LR
        step1["Get the data"] -->
        step2["Model the domain"] --> 
        step3["Select the identifier scheme"] -->
        step4["Apply data standards"] -->
        step5["Choose data vocabularies"] -->
        step6["Transform data for interoperability"] -->
        step7["Host your data"] -->
        step8["Share your data"]
