%%{init: {
  "htmlLabels": true,
  "flowchart": {
    "wrappingWidth": 110,
    "padding": 4,
    "rankSpacing": -1,
    "diagramPadding": 0,
    "nodeSpacing": 4,
    "text-align": "left"
  }
}}%%


flowchart LR;

    subgraph step1
        direction TB
        step1L@{ shape: processes, label: "**1.&nbsp;Get the data**" } -.-
        ft-data-access@{ shape: rect, label: "1.1&nbsp;Data access" } -.-
        ft-data-retrieval@{ shape: rect, label: "1.2&nbsp;Data retrieval" }
         -.->
        step1C@{ shape: notch-rect, label: "**Hosting environment capabilities**" }
    end

    subgraph step2
        direction TB
        step2L@{ shape: processes, label: "**2.&nbsp;Model the domain**" } -.-
        ft-identify-data-types@{ shape: rect, label: "2.1&nbsp;Identify data types" }
         -.->
        step2C@{ shape: notch-rect, label: "**Content & Context**" }
    end

    subgraph step3
        direction TB
        step3L@{ shape: processes, label: "**3.&nbsp;Select the identifier scheme**" } -.-
        ft-identifier-minting@{ shape: rect, label: "3.1&nbsp;Identifier minting" } -.-
        ft-identifier-reuse@{ shape: rect, label: "3.2&nbsp;Reusing community identifiers" }
         -.->
        step3C@{ shape: notch-rect, label: "**Content & Context**" }
    end

    subgraph step4
        direction TB
        step4L@{ shape: processes, label: "**4.&nbsp;Apply data standards**" } -.-
        ft-data-standards-reuse@{ shape: rect, label: "4.1&nbsp;Reusing existing data standards" } -.-
        ft-data-standards-development@{ shape: rect, label: "4.2&nbsp;Developing data standards" } -.-
        ft-apply-data-standards@{ shape: rect, label: "4.3&nbsp;Applying data standards" } -.-
        ft-validate-against-data-standards@{ shape: rect, label: "4.4&nbsp;Validating against data standards" }
         -.->
        step4C@{ shape: notch-rect, label: "**Representation and format**" }
    end

    subgraph step5
        direction TB
        step5L@{ shape: processes, label: "**5.&nbsp;Choose data vocabularies**" } -.-
        ft-select-data-vocabularies@{ shape: rect, label: "5.1&nbsp;Selecting data vocabularies" } -.-
        ft-develop-data-vocabularies@{ shape: rect, label: "5.2&nbsp;Developing data vocabularies" } -.-
        ft-anotate-with-data-vocabularies@{ shape: rect, label: "5.3&nbsp;Annotating with data vocabularies" } -.-
        ft-manage-vocabularies@{ shape: rect, label: "5.4&nbsp;Managing vocabularies" }
         -.->
        step5C@{ shape: notch-rect, label: "**Content & Context**" }
    end

    subgraph step6
        direction TB
        step6L@{ shape: processes, label: "**6.&nbsp;Transform data for inter-operability**" } -.-
        ft-identifier-mapping@{ shape: rect, label: "6.1&nbsp;Identifier mapping" } -.-
        ft-vocabulary-alignment@{ shape: rect, label: "6.2&nbsp;Vocabulary alignment" } -.-
        ft-data-model-mapping@{ shape: rect, label: "6.3&nbsp;Data model mapping" }
         -.->
        step6C@{ shape: notch-rect, label: "**Representation and format**" }
    end

    subgraph step7
        direction TB
        step7L@{ shape: processes, label: "**7.&nbsp;Host your data**" } -.-
        ft-data-hosting@{ shape: rect, label: "7.1&nbsp;Data hosting" } -.-
        ft-data-versioning@{ shape: rect, label: "7.2&nbsp;Data versioning" } -.-
        ft-data-transfer@{ shape: rect, label: "7.3&nbsp;Data transfer" }
         -.->
        step7C@{ shape: notch-rect, label: "**Hosting environment capabilities**" }
    end

    subgraph step8
        direction TB
        step8L@{ shape: processes, label: "**8.&nbsp;Share your data**" } -.-
        ft-data-licensing@{ shape: rect, label: "8.1&nbsp;Data licensing" } -.-
        ft-data-anonymisation@{ shape: rect, label: "8.2&nbsp;Data anonymisation" } -.-
        ft-data-release@{ shape: rect, label: "8.3&nbsp;Data release" }
         -.->
        step8C@{ shape: notch-rect, label: "**Hosting environment capabilities**" }
    end


step1 ~~~ step2 ~~~ step3 ~~~ step4 ~~~ step5 ~~~ step6 ~~~ step7 ~~~ step8

classDef hide fill:transparent,color:transparent,stroke:transparent,stroke-width:0px
class step1,step2,step3,step4,step5,step6,step7,step8 hide

classDef content-and-context fill:#1F3864,stroke:#1F3864,color:#FFFFFF,font-weight:bold
classDef representation-and-format fill:#A12964,stroke:#A12964,color:#FFFFFF,font-weight:bold
classDef hosting-environment-capabilities fill:#FF7D8D,stroke:#FF7D8D,color:#FFFFFF,font-weight:bold

class step1C,step7C,step8C hosting-environment-capabilities
class step2C,step3C,step5C content-and-context
class step4C,step6C representation-and-format

