%%{init: {
  "htmlLabels": true,
  "flowchart": {
    "wrappingWidth": 260
  }
}}%%
flowchart TB;
    goal@{ shape: doc, label: "FAIRification goal" }

    requirements@{ shape: doc, label: "Research object requirements" }

    capabilities@{ shape: doc, label: "FAIRification Capabilities" }

    resources@{ shape: doc, label: "FAIRification resources" }

    pre_assessment@{ shape: doc, label: "Pre-FAIRification assessment" }
    
    design@{ shape: doc, label: "Design decisions"} 

    implementation@{ shape: doc, label: "FAIRification task list"} 

    post_assessment@{ shape: doc, label: "Post-FAIRification assessment" }

    
    goal -- Used to determine --> requirements
    requirements -- Used to identify --> capabilities & resources
    requirements -- Used as basis for --> pre_assessment
    capabilities & resources & pre_assessment -- Used to inform --> design
    design -- Used to specify --> implementation
    requirements & implementation -- Used as basis for --> post_assessment
    post_assessment -- Used to inform --> design