flowchart LR;
    CA@{ shape: brace-r, label: "FAIR compliance challenge" } -.-
    A@{ shape: sm-circ, label: "Small start" } -->
    PhaseI["Define FAIRification Goal"] -->
    PhaseII["Project Examination"] -->
    PhaseIII["Iterative FAIRification Cycles"] -->
    PhaseIV["Post-FAIRification Review"] -->
    B@{ shape: framed-circle, label: "Stop" } -.-
    CB@{ shape: comment, label: "Intended use cases fulfilled!" }