%%{init: {
  "htmlLabels": true,
  "layout": "elk",
  "flowchart": { 
    "defaultRenderer": "elk",
    "wrappingWidth": 260,
    "padding":10,
    "diagramPadding": 10,
    "padding": 0, 
    "rankSpacing": 0,
    "nodeSpacing": 0
  }
}}%%
flowchart TB;

    %% Process phases
    phase_2("`**Project Examination**`")
    phase_4("`**Post-FAIRification Review**`")


    %% Process inputs
    fairification_roadmap@{ shape: doc, label: "**FAIRification roadmap**
    Current and projected states, requirements and gaps."}


    %% Process flow elements
    design_backlog@{ shape: card, label: "**Refined remediation backlog**
    Design decisions for identifiers, metadata, ontologies, supporting systems and research object sharing."} 

    implementation_tasks@{ shape: card, label: "**FAIRification task tracker**
    Planned, active and completed tasks, including responsibilities, status, dependencies, supporting resources and results."} 

    assessment_status@{ shape: card, label: "**Current state assessment report**
    Updated assessment of what has been put in place and which requirements/gaps remains to be addressed." }


    %% Process outputs
    fairification_updates@{ shape: docs, label: "**FAIRification updates**
    Design decisions, FAIRification task tracker record and assessment reports from each iteration.<br>" }


    %% Relations
    phase_2 --> phase_3_input
    fairification_roadmap -- Used to inform scope, design decisions and initial backlog --> phase_3_flow
    design_backlog -- "`Guides *implementation activities*`" --> implementation_tasks
    implementation_tasks -- "`Serves as the basis for *assessment activities*`" --> assessment_status
    assessment_status -- "`Informs remaining *design activities*`" --> design_backlog
    phase_3_flow --> phase_3_outputs
    fairification_updates -- Used as basis for accountability and lessons learned --> phase_4


    %% Structral elements
    subgraph phase_3_input["`**Input**`"]
        fairification_roadmap
    end

    subgraph phase_3_flow["`**Iterative FAIRification Cycles**`"]
        direction TB
        design_backlog
        implementation_tasks
        assessment_status
    end

    subgraph phase_3_outputs["`**Output**`"]
        fairification_updates
    end





