%%{init: {
  "htmlLabels": true,
  "flowchart": {
    "wrappingWidth": 260,
    "padding":10,
    "diagramPadding": 10,
    "padding": 0, 
    "rankSpacing": 0,
    "nodeSpacing": 0
  }
}}%%
flowchart TB;

    %% Process phases
    phase_1("`**Define FAIRification Goal**`")
    phase_2("`**Project Examination**`")
    phase_3("`**Iterative FAIRification Cycles**`")

    %% Process inputs
    fairification_goal@{ shape: doc, label: "**FAIRification goals**
    In terms of intended *usability of the research object* that isn’t currently possible. Also covering broader impact and value." }   
    
    fairification_roadmap@{ shape: doc, label: "**FAIRification roadmap**
    Current and projected states, requirements and gaps."}

    fairification_updates@{ shape: docs, label: "**FAIRification updates**
    Design decisions, FAIRification task tracker record and assessment reports from each iteration.<br>" }

    %% Process outputs
    fairification_story@{ shape: doc, label: "**FAIRification story**
    Structured case study report on key achievements, FAIR implementation approach, and lessons learned." }

    %% Process flow elements
    key_achievements@{ shape: card, label: "**Key achievements**
    In terms of the initial goals, including requirements met, uses enabled etc but also in terms of FAIR compliance improvements."}
    
    overview_of_the_FAIRification_processes@{ shape: card, label: "**FAIR implementation record**
    Structured overview of the design decisions and steps involved as well as an annotated manifest of references to new/updated research objects, resources and other outputs."}
    
    lessons_learned@{ shape: card, label: "**Lessons learned**
    Summary of any learnings from the FAIRification process, including suggested improvements to the framework or any of its supporting resources."}

    %% Relations
    fairification_goal -- "Used as benchmark to evaluate the overall success of the process" --> phase_4_flow
    fairification_roadmap -- "Used as basis for high-level post-implementation assessment" --> phase_4_flow
    fairification_updates -- "Used as basis for accountability and lessons learned" --> phase_4_flow
    phase_4_flow -- Recorded as a structured case study report --> phase_4_outputs
    fairification_story -- Used to identify improvements --> 
    use_1("`**Maintaining the FAIRification framework**`")
    fairification_story -- Used to develop content for --> 
    use_2("`**Contributing to FAIRification resources**`")
    phase_1 --> phase_4_input_a
    phase_2 --> phase_4_input_b
    phase_3 --> phase_4_input_c


    %% Structral elements
    subgraph phase_4_input_a["`**Input A**`"]
        fairification_goal
    end
    subgraph phase_4_input_b["`**Input B**`"]
        fairification_roadmap
    end
    subgraph phase_4_input_c["`**Input C**`"]
        fairification_updates
    end

    subgraph phase_4_flow["`**Post-FAIRification Review**`"]
        direction TB
        key_achievements
        overview_of_the_FAIRification_processes
        lessons_learned
    end

    subgraph phase_4_outputs["`**Output**`"]
        fairification_story
    end
